# Generated by Django 5.2.7 on 2025-10-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("funded", "Funded"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
